### ISSUE TITLE
Dashscript 1.0 To-do list

### ISSUE THREAD

**Issue by scientific-dev** [dashscript/dashscript#1]
# The todo list for dashscript.

The task list to complete to release Dashscript 1.0.

- [x] Make a fast and better lexer. 
- [x] Make an ast generator.
- [x] Make an ir implementation. 
- [x] Make a stack based vm.
- [ ] Make standard modules. (Completed but still needs work here)
- [ ] Async support for the program.
- [ ] Classes and instances management.

### Major changes
- #4 (Almost rewrote everything)
